### ISSUE TITLE
Patch frameworks_base.diff isn't needed (keylayouts)

### ISSUE THREAD

**Issue by ghost** [djeman/android_device_samsung_j3xnlte#11]
This patch isn't needed,

You need sec_touchscreen for keylayouts. it's better this way.

Like this : [sec_touchscreen.kl](https://github.com/remilia15/android_device_samsung_grandprimeve3g/blob/cm-14.1/keylayout/sec_touchscreen.kl)

And this : [grandprimeve3g.mk](https://github.com/remilia15/android_device_samsung_grandprimeve3g/blob/cm-14.1/grandprimeve3g.mk#L32)

(Recommendation of remilia15)

**Comment by djeman** [comment]
Fixed on this commit => https://github.com/djeman/android_device_samsung_j3xnlte/commit/4c3efd34e27a33120a0d3369a89656b214ae4a73

Thanks
