### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by adrian1234a** [djeman/android_device_samsung_j3xnlte#17]
this is on frameworks
target thumb C++: bluetooth.default <= system/bt/main/../btif/src/bluetoothTrack.cpp
target thumb C: bluetooth.default <= system/bt/main/../btif/src/btif_av.c
In file included from system/bt/main/../btif/include/btif_av.h:31:0,
                 from system/bt/main/../btif/src/btif_av.c:41:
system/bt/main/../btif/src/btif_av.c: In function 'btif_av_state_idle_handler':
system/bt/main/../btif/src/btif_av.c:520:27: warning: passing argument 1 of 'bt_av_sink_callbacks->audio_config_cb' from incompatible pointer type
                 HAL_CBACK(bt_av_sink_callbacks, audio_config_cb, &(req.peer_bd),
                           ^
system/bt/main/../btif/include/btif_common.h:63:9: note: in definition of macro 'HAL_CBACK'
         P_CB->P_CBACK(__VA_ARGS__);         \
         ^
system/bt/main/../btif/src/btif_av.c:520:27: note: expected 'struct bt_bdaddr_t *' but argument is of type 'UINT8 (*)[6]'
                 HAL_CBACK(bt_av_sink_callbacks, audio_config_cb, &(req.peer_bd),
                           ^
system/bt/main/../btif/include/btif_common.h:63:9: note: in definition of macro 'HAL_CBACK'
         P_CB->P_CBACK(__VA_ARGS__);         \
         ^
system/bt/main/../btif/src/btif_av.c: In function 'btif_av_state_opened_handler':
system/bt/main/../btif/src/btif_av.c:1073:13: warning: implicit declaration of function 'btif_hf_is_call_idle' [-Wimplicit-function-declaration]
             if ((!(btif_av_cb[index].flags & BTIF_AV_FLAG_PENDING_START)) && (!btif_hf_is_call_idle())) {
             ^
system/bt/main/../btif/src/btif_av.c: In function 'btif_av_check_rc_connection_priority':
system/bt/main/../btif/src/btif_av.c:2010:5: warning: implicit declaration of function 'bdaddr_to_string' [-Wimplicit-function-declaration]
     BTIF_TRACE_IMP("AVCTP Address : %s ", bdaddr_to_string(&peer_bda, &addr1,
     ^
system/bt/main/../btif/src/btif_av.c: At top level:
system/bt/main/../btif/src/btif_av.c:2509:1: warning: missing initializer for field 'audio_focus_state' of 'btav_interface_t' [-Wmissing-field-initializers]
 };
 ^
In file included from system/bt/main/../btif/src/btif_av.c:35:0:
hardware/libhardware/include/hardware/bt_av.h:128:13: note: 'audio_focus_state' declared here
     void  (*audio_focus_state)( int focus_state );
             ^
system/bt/main/../btif/src/btif_av.c:2521:1: warning: missing initializer for field 'audio_focus_state' of 'btav_interface_t' [-Wmissing-field-initializers]
 };
 ^
In file included from system/bt/main/../btif/src/btif_av.c:35:0:
hardware/libhardware/include/hardware/bt_av.h:128:13: note: 'audio_focus_state' declared here
     void  (*audio_focus_state)( int focus_state );
             ^
target Pack Relocations: libpower (/home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/SHARED_LIBRARIES/libpower_intermediates/PACKED/libpower.so)
INFO: Compaction                 : 0 bytes
INFO: Too few relocations to pack after alignment
target thumb C: libbtdevice <= system/bt/device/src/controller.c
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libLLVMCodeGen_intermediates/libLLVMCodeGen.a: member at 185380082 is not an ELF object
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libLLVMCodeGen_intermediates/libLLVMCodeGen.a: member at 185380142 is not an ELF object
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libLLVMCodeGen_intermediates/libLLVMCodeGen.a: member at 185380202 is not an ELF object
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libLLVMCodeGen_intermediates/libLLVMCodeGen.a: member at 185380262 is not an ELF object
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libLLVMObject_intermediates/libLLVMObject.a: member at 68842 is not an ELF object
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libLLVMObject_intermediates/libLLVMObject.a: member at 68902 is not an ELF object
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libLLVMObject_intermediates/libLLVMObject.a: member at 68962 is not an ELF object
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libLLVMObject_intermediates/libLLVMObject.a: member at 69022 is not an ELF object
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libLLVMObject_intermediates/libLLVMObject.a: member at 69082 is not an ELF object
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libLLVMObject_intermediates/libLLVMObject.a: member at 3143522 is not an ELF object
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libLLVMObject_intermediates/libLLVMObject.a: member at 3143582 is not an ELF object
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libLLVMObject_intermediates/libLLVMObject.a: member at 3143642 is not an ELF object
prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libLLVMObject_intermediates/libLLVMObject.a: member at 3143702 is not an ELF object
target Pack Relocations: libbt-vendor (/home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/SHARED_LIBRARIES/libbt-vendor_intermediates/PACKED/libbt-vendor.so)
INFO: Compaction                 : 0 bytes
INFO: Too few relocations to pack after alignment
target thumb C++: libwebviewchromium_plat_support <= frameworks/webview/chromium/plat_support/graphics_utils.cpp
target thumb C++: libwebviewchromium_plat_support <= frameworks/webview/chromium/plat_support/graphic_buffer_impl.cpp
Symlink: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/system/bin/app_process -> app_process32
Export includes file: frameworks/av/media/libstagefright/Android.mk -- /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/SHARED_LIBRARIES/libstagefright_intermediates/export_includes
Import includes file: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/SHARED_LIBRARIES/libstagefright_intermediates/import_includes
target thumb C++: libstagefright_omx <= frameworks/av/media/libstagefright/omx/GraphicBufferSource.cpp
target thumb C++: libstagefright_omx <= frameworks/av/media/libstagefright/omx/OMX.cpp
target thumb C++: libstagefright_omx <= frameworks/av/media/libstagefright/omx/OMXMaster.cpp
target thumb C++: libstagefright_omx <= frameworks/av/media/libstagefright/omx/OMXNodeInstance.cpp
target thumb C++: libstagefright_omx <= frameworks/av/media/libstagefright/omx/SimpleSoftOMXComponent.cpp
target thumb C++: libstagefright_omx <= frameworks/av/media/libstagefright/omx/SoftOMXComponent.cpp
target thumb C++: libstagefright_omx <= frameworks/av/media/libstagefright/omx/SoftOMXPlugin.cpp
target thumb C++: libstagefright_omx <= frameworks/av/media/libstagefright/omx/SoftVideoDecoderOMXComponent.cpp
target thumb C++: libstagefright_omx <= frameworks/av/media/libstagefright/omx/SoftVideoEncoderOMXComponent.cpp
target Pack Relocations: libstagefright_yuv (/home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/SHARED_LIBRARIES/libstagefright_yuv_intermediates/PACKED/libstagefright_yuv.so)
INFO: Compaction                 : 0 bytes
INFO: Too few relocations to pack after alignment
target thumb C++: libstagefright_color_conversion <= frameworks/av/media/libstagefright/colorconversion/ColorConverter.cpp
target thumb C++: libstagefright_color_conversion <= frameworks/av/media/libstagefright/colorconversion/SoftwareRenderer.cpp
target arm C++: libstagefright_aacenc <= frameworks/av/media/libstagefright/codecs/aacenc/AACEncoder.cpp
target thumb C++: libstagefright_matroska <= frameworks/av/media/libstagefright/matroska/MatroskaExtractor.cpp
target thumb C++: libstagefright_mediafilter <= frameworks/av/media/libstagefright/filters/GraphicBufferListener.cpp
target thumb C++: libstagefright_mediafilter <= frameworks/av/media/libstagefright/filters/MediaFilter.cpp
external/llvm/lib/CodeGen/SelectionDAG/FunctionLoweringInfo.cpp:440: error: undefined reference to 'llvm::parseEHActions(llvm::IntrinsicInst const*, llvm::SmallVectorImpl<llvm::ActionHandler*>&)'
Import includes file: /home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libstagefright_webm_intermediates/import_includes
target thumb C++: libstagefright_timedtext <= frameworks/av/media/libstagefright/timedtext/TextDescriptions.cpp
external/llvm/lib/CodeGen/CodeGen.cpp:71: error: undefined reference to 'llvm::initializeTwoAddressInstructionPassPass(llvm::PassRegistry&)'
external/llvm/lib/CodeGen/CodeGen.cpp:73: error: undefined reference to 'llvm::initializeUnreachableBlockElimPass(llvm::PassRegistry&)'
external/llvm/lib/CodeGen/CodeGen.cpp:74: error: undefined reference to 'llvm::initializeUnreachableMachineBlockElimPass(llvm::PassRegistry&)'
external/llvm/lib/CodeGen/CodeGen.cpp:75: error: undefined reference to 'llvm::initializeVirtRegMapPass(llvm::PassRegistry&)'
external/llvm/lib/CodeGen/CodeGen.cpp:76: error: undefined reference to 'llvm::initializeVirtRegRewriterPass(llvm::PassRegistry&)'
external/llvm/lib/CodeGen/CodeGen.cpp:77: error: undefined reference to 'llvm::initializeWinEHPreparePass(llvm::PassRegistry&)'
external/llvm/lib/CodeGen/InlineSpiller.cpp:1327: error: undefined reference to 'llvm::VirtRegMap::assignVirt2StackSlot(unsigned int)'
external/llvm/lib/CodeGen/InlineSpiller.cpp:1334: error: undefined reference to 'llvm::VirtRegMap::assignVirt2StackSlot(unsigned int, int)'
target thumb C++: libstagefright_timedtext <= frameworks/av/media/libstagefright/timedtext/TimedTextDriver.cpp
external/llvm/lib/CodeGen/LiveRangeEdit.cpp:390: error: undefined reference to 'llvm::VirtRegMap::grow()'
external/llvm/lib/CodeGen/LiveRegMatrix.cpp:36: error: undefined reference to 'llvm::initializeVirtRegMapPass(llvm::PassRegistry&)'
external/llvm/lib/CodeGen/LiveRegMatrix.cpp:47: error: undefined reference to 'llvm::VirtRegMap::ID'
external/llvm/lib/CodeGen/LiveRegMatrix.cpp:63: error: undefined reference to 'llvm::VirtRegMap::ID'
external/llvm/lib/CodeGen/LiveVariables.cpp:48: error: undefined reference to 'llvm::initializeUnreachableMachineBlockElimPass(llvm::PassRegistry&)'
external/llvm/lib/CodeGen/LiveVariables.cpp:56: error: undefined reference to 'llvm::UnreachableMachineBlockElimID'
external/llvm/lib/CodeGen/Passes.cpp:394: error: undefined reference to 'llvm::createUnreachableBlockEliminationPass()'
external/llvm/lib/CodeGen/Passes.cpp:432: error: undefined reference to 'llvm::createUnreachableBlockEliminationPass()'
external/llvm/lib/CodeGen/Passes.cpp:425: error: undefined reference to 'llvm::createWinEHPass(llvm::TargetMachine const*)'
external/llvm/lib/CodeGen/Passes.cpp:685: error: undefined reference to 'llvm::TwoAddressInstructionPassID'
external/llvm/lib/CodeGen/Passes.cpp:734: error: undefined reference to 'llvm::TwoAddressInstructionPassID'
external/llvm/lib/CodeGen/Passes.cpp:734: error: undefined reference to 'llvm::VirtRegRewriterID'
external/llvm/lib/CodeGen/RegAllocBasic.cpp:130: error: undefined reference to 'llvm::initializeVirtRegMapPass(llvm::PassRegistry&)'
external/llvm/include/llvm/ADT/SmallVector.h:114: error: undefined reference to 'llvm::VirtRegMap::ID'
external/llvm/lib/CodeGen/RegAllocBasic.cpp:291: error: undefined reference to 'llvm::VirtRegMap::ID'
target thumb C++: libstagefright_timedtext <= frameworks/av/media/libstagefright/timedtext/TimedText3GPPSource.cpp
external/llvm/lib/CodeGen/RegAllocGreedy.cpp:438: error: undefined reference to 'llvm::initializeVirtRegMapPass(llvm::PassRegistry&)'
external/llvm/lib/CodeGen/RegAllocGreedy.cpp:569: error: undefined reference to 'llvm::VirtRegMap::hasKnownPreference(unsigned int)'
external/llvm/lib/CodeGen/RegAllocGreedy.cpp:754: error: undefined reference to 'llvm::VirtRegMap::hasPreferredPhys(unsigned int)'
external/llvm/include/llvm/CodeGen/VirtRegMap.h:126: error: undefined reference to 'llvm::VirtRegMap::grow()'
target thumb C++: libstagefright_timedtext <= frameworks/av/media/libstagefright/timedtext/TimedTextSource.cpp
external/llvm/include/llvm/Object/Error.h:34: error: undefined reference to 'llvm::object::object_category()'
external/llvm/include/llvm/Object/Error.h:34: error: undefined reference to 'llvm::object::object_category()'
external/llvm/include/llvm/Object/Error.h:34: error: undefined reference to 'llvm::object::object_category()'
external/llvm/include/llvm/Object/Error.h:34: error: undefined reference to 'llvm::object::object_category()'
target thumb C++: libstagefright_timedtext <= frameworks/av/media/libstagefright/timedtext/TimedTextSRTSource.cpp
external/llvm/include/llvm/Object/ELF.h:548: error: undefined reference to 'llvm::object::getELFRelocationTypeName(unsigned int, unsigned int)'
external/llvm/include/llvm/Object/ELF.h:548: error: undefined reference to 'llvm::object::getELFRelocationTypeName(unsigned int, unsigned int)'
external/llvm/include/llvm/Object/ELF.h:548: error: undefined reference to 'llvm::object::getELFRelocationTypeName(unsigned int, unsigned int)'
external/llvm/include/llvm/Object/ELF.h:548: error: undefined reference to 'llvm::object::getELFRelocationTypeName(unsigned int, unsigned int)'
target thumb C++: libstagefright_timedtext <= frameworks/av/media/libstagefright/timedtext/TimedTextPlayer.cpp
external/llvm/lib/Object/MachOUniversal.cpp:60: error: undefined reference to 'llvm::object::Binary::getData() const'
external/llvm/lib/Object/MachOUniversal.cpp:73: error: undefined reference to 'llvm::object::Binary::getData() const'
external/llvm/lib/Object/MachOUniversal.cpp:75: error: undefined reference to 'llvm::object::Binary::getFileName() const'
external/llvm/lib/Object/MachOUniversal.cpp:77: error: undefined reference to 'llvm::object::ObjectFile::createMachOObjectFile(llvm::MemoryBufferRef)'
external/llvm/lib/Object/MachOUniversal.cpp:87: error: undefined reference to 'llvm::object::Binary::getData() const'
external/llvm/lib/Object/MachOUniversal.cpp:89: error: undefined reference to 'llvm::object::Binary::getFileName() const'
external/llvm/lib/Object/MachOUniversal.cpp:91: error: undefined reference to 'llvm::object::Archive::create(llvm::MemoryBufferRef)'
external/llvm/lib/Object/MachOUniversal.cpp:108: error: undefined reference to 'llvm::object::Binary::Binary(unsigned int, llvm::MemoryBufferRef)'
external/llvm/lib/Object/MachOUniversal.cpp:114: error: undefined reference to 'llvm::object::Binary::getData() const'
external/llvm/include/llvm/Object/MachOUniversal.h:29: error: undefined reference to 'llvm::object::Binary::~Binary()'
/home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/STATIC_LIBRARIES/libLLVMObject_intermediates/libLLVMObject.a(MachOUniversal.o):external/llvm/lib/Object/MachOUniversal.cpp:vtable for llvm::object::MachOUniversalBinary: error: undefined reference to 'llvm::object::Binary::~Binary()'
external/llvm/lib/Object/ObjectFile.cpp:80: error: undefined reference to 'llvm::object::ObjectFile::createMachOObjectFile(llvm::MemoryBufferRef)'
external/llvm/lib/Object/ObjectFile.cpp:84: error: undefined reference to 'llvm::object::ObjectFile::createCOFFObjectFile(llvm::MemoryBufferRef)'
external/llvm/lib/Object/SymbolicFile.cpp:23: error: undefined reference to 'llvm::object::Binary::Binary(unsigned int, llvm::MemoryBufferRef)'
external/llvm/lib/Object/SymbolicFile.cpp:25: error: undefined reference to 'llvm::object::Binary::~Binary()'
external/llvm/lib/Object/SymbolicFile.cpp:25: error: undefined reference to 'llvm::object::Binary::~Binary()'
external/llvm/lib/Object/SymbolicFile.cpp:69: error: undefined reference to 'llvm::object::IRObjectFile::findBitcodeInObject(llvm::object::ObjectFile const&)'
external/llvm/lib/Object/SymbolicFile.cpp:73: error: undefined reference to 'llvm::object::IRObjectFile::create(llvm::MemoryBufferRef, llvm::LLVMContext&)'
external/llvm/lib/Object/SymbolicFile.cpp:36: error: undefined reference to 'llvm::object::IRObjectFile::create(llvm::MemoryBufferRef, llvm::LLVMContext&)'
target thumb C++: libstagefright_mpeg2ts <= frameworks/av/media/libstagefright/mpeg2ts/AnotherPacketSource.cpp
target thumb C++: libstagefright_mpeg2ts <= frameworks/av/media/libstagefright/mpeg2ts/ATSParser.cpp
target thumb C++: libstagefright_mpeg2ts <= frameworks/av/media/libstagefright/mpeg2ts/ESQueue.cpp
target thumb C++: libstagefright_mpeg2ts <= frameworks/av/media/libstagefright/mpeg2ts/MPEG2PSExtractor.cpp
target thumb C++: libstagefright_mpeg2ts <= frameworks/av/media/libstagefright/mpeg2ts/MPEG2TSExtractor.cpp
external/llvm/lib/ProfileData/CoverageMappingReader.cpp:436: error: undefined reference to 'llvm::object::createBinary(llvm::MemoryBufferRef, llvm::LLVMContext*)'
target thumb C++: libstagefright_id3 <= frameworks/av/media/libstagefright/id3/ID3.cpp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
build/core/shared_library_internal.mk:80: fallo en las instrucciones para el objetivo '/home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/SHARED_LIBRARIES/libLLVM_intermediates/LINKED/libLLVM.so'
make: *** [/home/adrian1234a/Android/RR/out/target/product/j3xnlte/obj/SHARED_LIBRARIES/libLLVM_intermediates/LINKED/libLLVM.so] Error 1
make: *** Se espera a que terminen otras tareas....
make: se sale del directorio '/home/adrian1234a/Android/RR'

**Comment by djeman** [comment]
patches problem ? ^^
