### ISSUE TITLE
init files in ramdisk problem

### ISSUE THREAD

**Issue by AndiNR** [djeman/android_device_samsung_j3xnlte#22]
Hii @djeman i have some problem in init ramdisk ..

Im build lineage13 for some device with same chip like j3xnlte , i have apply patch and change name libinitj3lte.cpp with my device , after build success stuck at logo . ok i change init file in ramdisk from other device with base cm13/lineage13 its not stuck at logo but stuck bootanime ..
My question  .
How ti fix my problem in init files ramdisk .. 

Note : compiled twrp success no problem or bug .. Only init ramdisl in boot.img problem cant boot

Thanks

**Comment by djeman** [comment]
Yop,

It can be a lot of problem, you need to build an eng version to get adb enabled by default at boot and after you can see errors in the logcat easily.

**Comment by AndiNR** [comment]
with brunch lineage_mydevice-eng ??

**Comment by djeman** [comment]
Yes it's that, replace userdebug by eng.
https://source.android.com/source/building#choose-a-target

Engineering build have more tools to debug and adb enabled at boot by default.
After with the android device monitor or an other tool on your pc you can debug your android boot.
https://developer.android.com/studio/profile/monitor.html

**Comment by AndiNR** [comment]
One question ..
Only apply patch from device tree right ??

Can you test my build boot.img j3 for lnos13 for test booting or not ..
I want see problem in my source or something ..

If you have telgram I want chat with you ..

Thanks..

**Comment by parthibx24** [comment]
@AndiNR Maybe its a source problem.if your using compressed source from skadoosh like me then its better to update the source using this command. "repo sync -c -f --force-sync --no-clone-bundle --no-tags -j4 ".
i also faced problem with that source and after updating the source it got fixed.

**Comment by AndiNR** [comment]
Im always update repo if used from compressed ..

**Comment by Kompwu** [comment]
@AndiNR Can you close this issue ?
