### ISSUE TITLE
Support for J320M

### ISSUE THREAD

**Issue by weidsom** [djeman/android_device_samsung_j3xnlte#24]
Hello, sorry to call here but I did not find any contact, could you add support for the J320M? Or provide an idea of how to do?

**Comment by Borksek** [comment]
Github issues exist for YOU to fix them and the creator to add them into the commits. So if you don't have a valuable fix that works, djeman won't try. And correct me if I'm wrong but j320m support already exist.

-Borksek

**Comment by weidsom** [comment]
So, look issues are for reporting!

Pull Request are to send solutions and/or implementations.

Thanks for your useless reply but I've already developed my rom from scratch. 
and just to answer: there is no support for the J320M the rom does not start at all.
