### ISSUE TITLE
What happend to the normal files?

### ISSUE THREAD

**Issue by Lankezz** [djeman/android_device_samsung_j3xnlte#27]
What happend to device.mk and those other files that were here before?

**Comment by djeman** [comment]
On the cm14.1 I divided the device tree in 3 device trees.
A common device tree => https://github.com/djeman/android_device_samsung_sharkls-common
And 2 device trees that use the common : 
j3xlte (sm-j320f/g/m) => https://github.com/djeman/android_device_samsung_j3xlte
j3xnlte (sm-j320fn) => https://github.com/djeman/android_device_samsung_j3xnlte

The kernel repository was renamed to sharkls => https://github.com/djeman/android_kernel_samsung_sharkls

The device.mk is become in the independant device tree files j3xnlte.mk and j3xlte.mk and this 2 files include the sharkls.mk in the common device tree. 
I only normalized all names and removed useless files.

Sorry for the big change but the sm-j320m needs the kernel configured for the j3xlte so it was the good moment to make more proper sources/device trees for this 2 devices :)

I will make the same change on los15 ... when I have the time.

**Comment by Lankezz** [comment]
Thanks alot djeman

**Comment by Mikdadali** [comment]
why this error comes?
https://del.dog/atijiguygn
